//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LodgeMinutes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LodgeMinutes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An amendment to the motion was made by ({0}) and seconded by {1} to ({2}).{3}\nThe amendment {4}..
        /// </summary>
        internal static string amendmentMade {
            get {
                return ResourceManager.GetString("amendmentMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,By Dispensation of the Grand Master&apos;.
        /// </summary>
        internal static string byDispensation {
            get {
                return ResourceManager.GetString("byDispensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A motion was made by ({0}) and seconded by {1} to ({2}).{3}\nThe motion {4}..
        /// </summary>
        internal static string motionMade {
            get {
                return ResourceManager.GetString("motionMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Regular Communication, of {0} was held in the {1}, on {2}. Lodge was opened on the {3} dergree, {4} by {5}, at {6}
        ///
        ///.
        /// </summary>
        internal static string regularOpen {
            get {
                return ResourceManager.GetString("regularOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Special Communication, of {0} was held in the {1}, on {2}. Lodge was opened on the {3} dergree, {4} by {5}, at {6}.
        /// </summary>
        internal static string specialOpen {
            get {
                return ResourceManager.GetString("specialOpen", resourceCulture);
            }
        }
    }
}
